### ISSUE TITLE
Spigot 1.9 incompatibility - plugin does not start

### ISSUE THREAD

**Issue by tmad40blue** [chaseoes/PingChat#1]
@chaseoes 

Hi, looks like PingChat is not loading using Spigot 1.9 - the stacktrace is below:

```
[14:54:25 WARN]: Exception in thread "Craft Scheduler Thread - 284" 
[14:54:25 WARN]: org.apache.commons.lang.UnhandledException: Plugin PingChat v1.3 generated an exception while executing task 12
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
        at org.mcstats.Metrics.postPlugin(Metrics.java:335)
        at org.mcstats.Metrics.access$400(Metrics.java:57)
        at org.mcstats.Metrics$1.run(Metrics.java:223)
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
```

This is related to getOnlinePlayers() being a deprecated method in Spigot 1.9. May be possible to temporarily fix with the method outlined [here](https://www.spigotmc.org/threads/minecraft-1-9-release.127186/) related to SpecialSource. Haven't tested it myself.

Thanks!

**Comment by chaseoes** [comment]
Fixed as of d5eef59b14da1ce9fd796d1aaf99c80009e5850f.

Download awaiting approval on BukkitDev: 
http://dev.bukkit.org/bukkit-plugins/pingchat/files/6-ping-chat-v1-4/
