### ISSUE TITLE
1.9 incompatibility - Sound enum has changed

### ISSUE THREAD

**Issue by tmad40blue** [chaseoes/PingChat#2]
Hi, the sound enum has changed for 1.9 and PingChat can no longer play sounds. Stacktrace below:

```
[20:06:44 WARN]: [PingChat] Task #2485919 for PingChat v1.3 generated an exception
java.lang.IllegalArgumentException: No enum constant org.bukkit.Sound.ORB_PICKUP
        at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_66]
        at org.bukkit.Sound.valueOf(Sound.java:1) ~[spigot.jar:git-Spigot-1a196e1-f8e38f2]
        at com.chaseoes.pingchat.PingChat.ping(PingChat.java:61) ~[?:?]
        at com.chaseoes.pingchat.PingChat$1.run(PingChat.java:51) ~[?:?]
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-1a196e1-f8e38f2]
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-1a196e1-f8e38f2]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729) [spigot.jar:git-Spigot-1a196e1-f8e38f2]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-1a196e1-f8e38f2]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-Spigot-1a196e1-f8e38f2]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-1a196e1-f8e38f2]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
```

**Comment by chaseoes** [comment]
Fixed as of d5eef59b14da1ce9fd796d1aaf99c80009e5850f.
